openapi: "3.0.0"
info:
    title: "Proxy API"
    version: "1.0.0"
    license:
        name: "Internal"
        url: "http://localhost"
servers:
    - url: "http://localhost"
security:
    - {}
paths:
    "/tenants/{tenant-id}/profiles/{profile-id}":
        get:
            x-proxy:
                name: profile
            summary: "get profile"
            operationId: "profile-GetProfile"
            responses:
                "200":
                    $ref: '#/components/responses/profile-Profile'
                "404":
                    $ref: '#/components/responses/profile-ProfileNotFound'
                "500":
                    description: "Error"
                    content:
                        application/json:
                            schema:
                                properties:
                                    message:
                                        $ref: '#/components/schemas/profile-ZeroableString'
            parameters:
                - name: tenant-id
                  required: true
                  in: path
                  schema:
                    $ref: '#/components/schemas/profile-UUID'
                - $ref: '#/components/parameters/profile-ProfileID'
                - name: "some-query"
                  in: query
                  required: false
                  schema:
                    type: string
    "/profiles/{profile-id}":
        get:
            x-proxy:
                name: profile
                path: /tenants/{tenant-id}/profiles/{profile-id}
                method: get
                inject:
                    parameters:
                        - name: tenant-id
                          in: path
            summary: "get profile"
            operationId: "GetProfile"
            responses:
                "200":
                    $ref: '#/components/responses/profile-Profile'
                "404":
                    $ref: '#/components/responses/profile-ProfileNotFound'
                "500":
                    description: "Error"
                    content:
                        application/json:
                            schema:
                                properties:
                                    message:
                                        $ref: '#/components/schemas/profile-ZeroableString'
            parameters:
                - name: "validate"
                  in: query
                  required: false
                  schema:
                    $ref: "#/components/schemas/ZeroableBoolean"
                - $ref: '#/components/parameters/profile-ProfileID'
                - name: "some-query"
                  in: query
                  required: false
                  schema:
                    type: string
        put:
            x-proxy:
                name: profile
                path: /tenants/{tenant-id}/profiles/{profile-id}
                method: put
                inject:
                    parameters:
                        - name: tenant-id
                          in: path
            summary: "Create/Update profile"
            operationId: PutProfile
            requestBody:
                $ref: '#/components/requestBodies/profile-Profile'
            responses:
                "201":
                    description: success
                    content:
                        "application/json":
                            schema:
                                $ref: '#/components/schemas/profile-Profile'
                "400":
                    description: bad request
            parameters:
                - $ref: '#/components/parameters/profile-ProfileID'
                - name: "some-query"
                  in: query
                  required: false
                  schema:
                    type: string
    "/validated-profiles/{profile-id}":
        get:
            x-proxy:
                name: profile
                path: /tenants/{tenant-id}/profiles/{profile-id}
                method: get
                inject:
                    parameters:
                        - name: tenant-id
                          in: path
            summary: "get profile"
            operationId: "GetValidatedProfile"
            responses:
                "200":
                    $ref: '#/components/responses/profile-Profile'
                "404":
                    $ref: '#/components/responses/profile-ProfileNotFound'
                "500":
                    description: "Error"
                    content:
                        application/json:
                            schema:
                                properties:
                                    message:
                                        $ref: '#/components/schemas/profile-ZeroableString'
            parameters:
                - $ref: '#/components/parameters/profile-ProfileID'
                - name: "some-query"
                  in: query
                  required: false
                  schema:
                    type: string
components:
    schemas:
        profile-UUID:
            type: string
            format: uuid
            x-go-type-skip-optional-pointer: true
        profile-ZeroableString:
            type: string
            x-go-type-skip-optional-pointer: true
        profile-Profile:
            properties:
                id:
                    $ref: '#/components/schemas/profile-UUID'
                tenant_id:
                    $ref: '#/components/schemas/profile-UUID'
                nin:
                    $ref: '#/components/schemas/profile-ZeroableString'
                name:
                    $ref: '#/components/schemas/profile-ZeroableString'
                email:
                    $ref: '#/components/schemas/profile-ZeroableString'
                phone:
                    $ref: '#/components/schemas/profile-ZeroableString'
                dob:
                    $ref: '#/components/schemas/profile-ZeroableTime'
        profile-ZeroableTime:
            type: string
            format: date-time
            x-go-type-skip-optional-pointer: true
        ZeroableBoolean:
            type: boolean
    responses:
        profile-Profile:
            description: "success"
            headers:
                TraceID:
                    $ref: '#/components/headers/profile-TraceID'
            content:
                "application/json":
                    schema:
                        $ref: '#/components/schemas/profile-Profile'
        profile-ProfileNotFound:
            $ref: '#/components/responses/profile-Error'
        profile-Error:
            description: "not found"
            content:
                "application/json":
                    schema:
                        properties:
                            id:
                                $ref: '#/components/schemas/profile-UUID'
    parameters:
        profile-ProfileID:
            name: profile-id
            in: path
            required: true
            schema:
                $ref: '#/components/schemas/profile-UUID'
    requestBodies:
        profile-Profile:
            required: true
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/profile-Profile'
    headers:
        profile-TraceID:
            schema:
                $ref: '#/components/schemas/profile-ZeroableString'
    x-proxy:
        profile:
            spec: ./spec-profile.yml
