package cmd

import (
	"log"

	"github.com/telkomindonesia/oapik/internal/bundle"
)

type Bundle struct {
	Input  string `arg:"" help:"path to main OAS file"`
	Output string `arg:"" help:"path to generated OAS file" optional:"" `
}

func (b Bundle) Run(ctx Context) error {
	bytes, err := bundle.File(b.Input)
	if err != nil {
		log.Fatalln("fail to bundle file:", err)
	}

	bytes = append([]byte("# Code generated by oapik. DO NOT EDIT.\n"), bytes...)
	if err = write(b.Output, bytes); err != nil {
		log.Fatalln(err)
	}
	return nil
}
